# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2017 Rockchip Electronics Co., Ltd

obj-$(CONFIG_AK37E_GPIO) += ak37e_gpio.o
obj-$(CONFIG_AK3918AV100_GPIO) += ak3918av100_gpio.o
obj-$(CONFIG_AK37D_GPIO) += ak37d_gpio.o
obj-$(CONFIG_AK39EV33X_GPIO) += ak39ev33x_gpio.o
obj-$(CONFIG_AK39EV200_GPIO) += ak39ev200_gpio.o
obj-$(CONFIG_AK3918EV300L_GPIO) += ak3918ev300l_gpio.o
obj-$(CONFIG_KM01A_GPIO) += km01a_gpio.o
obj-$(CONFIG_AK3918AV130_GPIO) += ak3918av130_gpio.o