[camera]
#mode = 0(none) / 1(vertical) / 2(horizontal)
mode = 0
sensor_cnt = 1

[single_cfg]

#single config
isp_conf = /etc/config/isp_sc3332_mipi_2lane_av130.conf
#single_dev为非拼接单路设备0/1/2
single_dev = 0

[stitch]
#mode = 1/2 stich_num有效
stitch_num = 2

#conf数由stitch_num决定
isp_conf0 = /mnt/isp.conf
isp_conf1 = /mnt/isp.conf

[video0]
#code_type = h.264 / h.265
code_type                      = h.264
width                          = 1920
height                         = 1080
fps                            = 20
target_kbps                    = 2048


[video1]
code_type                      = h.264
width                          = 640
height                         = 360
fps                            = 20
target_kbps                    = 400

[audio]

#code_type = g711a / g711u / aac
code_type   = aac
sample_rate = 16000
