# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2017 Rockchip Electronics Co., Ltd

obj-$(CONFIG_PINCTRL_AK37E) += pinctrl-ak37e.o
obj-$(CONFIG_PINCTRL_AK37D) += pinctrl-ak37d.o
obj-$(CONFIG_PINCTRL_AK39EV33X) += pinctrl-ak39ev33x.o
obj-$(CONFIG_PINCTRL_AK3918AV100) += pinctrl-ak3918av100.o
obj-$(CONFIG_PINCTRL_AK3918AV130) += pinctrl-ak3918av130.o
obj-$(CONFIG_PINCTRL_AK3918EV300L) += pinctrl-ak3918ev300l.o
obj-$(CONFIG_PINCTRL_AK39EV200) += pinctrl-ak39ev200.o
obj-$(CONFIG_PINCTRL_KM01A) += pinctrl-km01a.o