#
# Anyka Clock specific Makefile
#
obj-$(CONFIG_MACH_AK37D) += ak37d_clk.o
obj-$(CONFIG_MACH_AK39EV330) += ak39ev330_clk.o
obj-$(CONFIG_MACH_AK37E) += ak37e_clk.o

obj-$(CONFIG_MACH_AK3918AV100) +=  ak3918av100_fixed_clk.o
obj-$(CONFIG_MACH_AK3918AV100) +=  ak3918av100_factor_clk.o
obj-$(CONFIG_MACH_AK3918AV100) +=  ak3918av100_gate_clk.o
obj-$(CONFIG_MACH_AK3918AV100) +=  ak3918av100_mux_clk.o

obj-$(CONFIG_MACH_AK3918EV300L) +=  ak3918av100_fixed_clk.o
obj-$(CONFIG_MACH_AK3918EV300L) +=  ak3918av100_factor_clk.o
obj-$(CONFIG_MACH_AK3918EV300L) +=  ak3918av100_gate_clk.o
obj-$(CONFIG_MACH_AK3918EV300L) +=  ak3918av100_mux_clk.o
obj-$(CONFIG_MACH_AK3918EV300L) +=  ak3918ev300l_uv_det.o

obj-$(CONFIG_MACH_AK3918AV130) +=  ak3918av100_fixed_clk.o
obj-$(CONFIG_MACH_AK3918AV130) +=  ak3918av100_factor_clk.o
obj-$(CONFIG_MACH_AK3918AV130) +=  ak3918av100_gate_clk.o
obj-$(CONFIG_MACH_AK3918AV130) +=  ak3918av100_mux_clk.o

obj-$(CONFIG_MACH_KM01A) +=  ak3918av100_fixed_clk.o
obj-$(CONFIG_MACH_KM01A) +=  ak3918av100_factor_clk.o
obj-$(CONFIG_MACH_KM01A) +=  ak3918av100_gate_clk.o
obj-$(CONFIG_MACH_KM01A) +=  ak3918av100_mux_clk.o
