# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#

obj-y	+= ak_clock.o ak_interrupts.o ak_l2buf.o ak_module_reset.o ak_timer.o 
