#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "cJSON.h"

int main() {
    // 测试解析一个更复杂的JSON字符串，类似于我们将要处理的DSS配置
    const char *test_json = "{\n"
        "  \"qs_vi_info\": [\n"
        "    {\n"
        "      \"qs_vi_dev_info\": {\n"
        "        \"dev_id\": 0,\n"
        "        \"enable\": 1,\n"
        "        \"isp_id\": 0,\n"
        "        \"isp_path\": \"/tmp/isp.conf\",\n"
        "        \"crop\": {\n"
        "          \"left\": 0,\n"
        "          \"top\": 0,\n"
        "          \"width\": 1920,\n"
        "          \"height\": 1080\n"
        "        },\n"
        "        \"frame_rate\": 30,\n"
        "        \"mirror_en\": 0,\n"
        "        \"flip_en\": 0,\n"
        "        \"isp_3dnr_format\": 0,\n"
        "        \"isp_3dnr_buf_len\": {\n"
        "          \"isp_3dnr_total_len\": 1024\n"
        "        },\n"
        "        \"ircut_group_id\": 0,\n"
        "        \"led_group_id\": 0,\n"
        "        \"lumen_group_id\": 0,\n"
        "        \"fastae_info\": {\n"
        "          \"bining_mode\": 0,\n"
        "          \"fastae_mode\": 1,\n"
        "          \"ae_stable_range\": 10,\n"
        "          \"night_mode_light_select\": 0,\n"
        "          \"daynight_threshold\": [100, 200],\n"
        "          \"daynight_master_id\": -1,\n"
        "          \"ae_table_file\": \"/tmp/ae_table.dat\"\n"
        "        }\n"
        "      },\n"
        "      \"qs_vi_chn_info\": [\n"
        "        {\n"
        "          \"dev_id\": 0,\n"
        "          \"chn_id\": 0,\n"
        "          \"enable\": 1,\n"
        "          \"frame_rate\": 30,\n"
        "          \"res\": {\n"
        "            \"width\": 1920,\n"
        "            \"height\": 1080\n"
        "          },\n"
        "          \"frame_depth\": 3,\n"
        "          \"data_type\": 0,\n"
        "          \"mode\": 0,\n"
        "          \"crop\": {\n"
        "            \"left\": 0,\n"
        "            \"top\": 0,\n"
        "            \"width\": 1920,\n"
        "            \"height\": 1080\n"
        "          },\n"
        "          \"max_res\": {\n"
        "            \"width\": 1920,\n"
        "            \"height\": 1080\n"
        "          },\n"
        "          \"stitch_attr\": {\n"
        "            \"stitch_mode\": 0,\n"
        "            \"stitch_num\": 0,\n"
        "            \"stitch_index\": 0,\n"
        "            \"stitch_global_id\": 0\n"
        "          }\n"
        "        }\n"
        "      ]\n"
        "    }\n"
        "  ],\n"
        "  \"qs_venc_info\": [\n"
        "    {\n"
        "      \"venc_id\": 0,\n"
        "      \"width\": 1920,\n"
        "      \"height\": 1080,\n"
        "      \"fps\": 30,\n"
        "      \"goplen\": 30,\n"
        "      \"target_kbps\": 2048,\n"
        "      \"max_kbps\": 4096,\n"
        "      \"profile\": 1,\n"
        "      \"br_mode\": 1,\n"
        "      \"initqp\": 26,\n"
        "      \"minqp\": 20,\n"
        "      \"maxqp\": 50,\n"
        "      \"jpeg_qlevel\": 80,\n"
        "      \"chroma_mode\": 0,\n"
        "      \"enc_out_type\": 0,\n"
        "      \"max_picture_size\": 0,\n"
        "      \"enc_level\": 0,\n"
        "      \"smart_mode\": 0,\n"
        "      \"smart_goplen\": 0,\n"
        "      \"smart_quality\": 0,\n"
        "      \"smart_static_value\": 0,\n"
        "      \"gdr_mode\": 0,\n"
        "      \"max_frame_size\": 0\n"
        "    }\n"
        "  ],\n"
        "  \"qs_video_info\": [\n"
        "    {\n"
        "      \"chn_id\": 0,\n"
        "      \"venc_id\": 0,\n"
        "      \"frame_rate\": 30,\n"
        "      \"frame_depth\": 3,\n"
        "      \"venc_encode_mode\": 1\n"
        "    }\n"
        "  ],\n"
        "  \"isp_info\": [\n"
        "    {\n"
        "      \"isp_id\": 0,\n"
        "      \"isp_path\": \"/tmp/isp.conf\"\n"
        "    }\n"
        "  ],\n"
        "  \"ircut\": [\n"
        "    {\n"
        "      \"ircut_a_gpio\": {\n"
        "        \"nb\": 10,\n"
        "        \"value\": 1\n"
        "      },\n"
        "      \"ircut_b_gpio\": {\n"
        "        \"nb\": -1,\n"
        "        \"value\": 0\n"
        "      }\n"
        "    }\n"
        "  ],\n"
        "  \"led\": [\n"
        "    {\n"
        "      \"ircut_led_type\": 0,\n"
        "      \"irled_gpio\": {\n"
        "        \"nb\": 11,\n"
        "        \"value\": 1\n"
        "      },\n"
        "      \"whiteled_type\": 0,\n"
        "      \"whiteled_gpio\": {\n"
        "        \"nb\": 12,\n"
        "        \"value\": 1\n"
        "      }\n"
        "    }\n"
        "  ],\n"
        "  \"hw_lumi_sensor\": [\n"
        "    {\n"
        "      \"ain_index\": 0,\n"
        "      \"daynight_threshold\": 1000\n"
        "    }\n"
        "  ]\n"
        "}";
        
    printf("Parsing JSON...\n");
    
    cJSON *parsed = cJSON_Parse(test_json);
    if (parsed == NULL) {
        const char *error_ptr = cJSON_GetErrorPtr();
        if (error_ptr != NULL) {
            printf("Error parsing JSON: %s\n", error_ptr);
            // 计算错误位置
            int pos = error_ptr - test_json;
            printf("Error position: %d\n", pos);
        }
        return 1;
    }
    
    printf("JSON parsed successfully!\n");
    
    // 释放内存
    cJSON_Delete(parsed);
    
    return 0;
}
