# SPDX-License-Identifier: GPL-2.0+

obj-$(CONFIG_CLK_ANYKA_37E) += clk-ak37e.o
obj-$(CONFIG_CLK_ANYKA_37D) += clk-ak37d.o
obj-$(CONFIG_CLK_ANYKA_39EV33X) += clk-ak39ev33x.o
obj-$(CONFIG_CLK_ANYKA_3918AV100) += clk-ak3918av100.o
obj-$(CONFIG_CLK_ANYKA_3918AV130) += clk-ak3918av130.o
obj-$(CONFIG_CLK_ANYKA_39EV200) += clk-ak39ev200.o
obj-$(CONFIG_CLK_ANYKA_3918EV300L) += clk-ak3918ev300l.o
obj-$(CONFIG_CLK_ANYKA_KM01A) += clk-km01a.o
