obj-$(CONFIG_RPMSG)		+= rpmsg_core.o
obj-$(CONFIG_ANYKA_RPMSG_ARM9L)	+= rpmsg_client_arm9l.o
obj-$(CONFIG_RPMSG_CHAR)	+= rpmsg_char.o
obj-$(CONFIG_RPMSG_VIRTIO)	+= virtio_rpmsg_bus.o
obj-$(CONFIG_RPMSG_CTRL)	        += rpmsg_client.o
obj-$(CONFIG_RPMSG_CTRL)	        += rpmsg_ctrl.o
