# SPDX-License-Identifier: GPL-2.0

spinand-objs := core.o gigadevice.o macronix.o micron.o winbond.o foress.o xtx.o fm_micro.o heyangtek.o gsto.o dosilicon.o ak_sfc_ctrl_drv.o ak_clk_tree_drv.o ak_spi_nand.o
obj-$(CONFIG_MTD_SPI_NAND) += spinand.o
