# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2012
# Texas Instruments Incorporated - http://www.ti.com/
# Aneesh V <aneesh@ti.com>
# Based on common/Makefile.
#
# sd upgrade flash
obj-y += fat-nor-uclass.o
obj-y += custom_upgrade.o
obj-y += fat_file_load.o
